spring.application.name=mint
server.port=40000

spring.datasource.url=jdbc:oracle:thin:@196.219.86.38:1521:orcl?charSet=UTF-8

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jackson.date-format=dd-MMM-yy

server.servlet.encoding.charsets=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE